<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Login Help</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/sign_up.css">
  </head>
  <body>
    <div class="signup-form">
      <h1>Recover Your Password</h1>

      <form method="POST" class="my-login-validation" action="forgot_password_emailer.php">
        <div class="form-group">
          <label class="control-label col-xs-4">Enter your username</label>
          <div class="col-xs-8">
            <input type="text" class="form-control" id="username" name="username" required>
          </div>
          <br>
          <button type="submit" class="button">Recover Password</button>
        </div>
      </div>
  </body>
</html>
