<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Reset Password</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/index.css">
  </head>
  <body>
    <?php
        if($this->flag == 0) {
          echo "One or more of the provided answers was incorrect.";
        } else {
          echo "<div>
                <header>Enter a new password</header>
                <form method='POST' action='password_success.php'>
                  <div>
                    <label>New Password</label>
                    <input type='password' name='password' required>
                    <label>Confirm Password</label>
                    <input type='password' name='passwordConfirm' required>
                    <input type='hidden' name='username' value='$this->username'>
                  </div>
                <button type='submit'>Proceed</button>";
        }
    ?>
  </body>
</html>