<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Sign Up - Company X</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="../../css/sign_up.css">
  <script src="https://www.google.com/recaptcha/api.js" async defer></script>
</head>

<body>
  <div class="signup-form">
    <form action="sign_up.php" method="POST" class="form-horizontal" onsubmit="return checkForm(this);">
      <div class="col-xs-8 col-xs-offset-4">
        <h2>Sign Up</h2>
      </div>
      <div class="form-group">
        <label class="control-label col-xs-4">First Name</label>
        <div class="col-xs-8">
          <input type="text" class="form-control" id="firstName" name="firstName" required>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-xs-4">Last Name</label>
        <div class="col-xs-8">
          <input type="text" class="form-control" id="lastName" name="lastName" required>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-xs-4">Email Address</label>
        <div class="col-xs-8">
          <input type="email" class="form-control" id="email" name="email" required>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-xs-4">Username</label>
        <div class="col-xs-8">
          <input type="text" class="form-control" id="username" name="username" required>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-xs-4">Password</label>
        <div class="col-xs-8">
          <input type="password" class="form-control" id="password" name="password" required>
          <ul class="input-requirements">
            <li>At least 8 characters long (and less than 100 characters)</li>
            <li>Contains at least 1 number</li>
            <li>Contains at least 1 lowercase letter</li>
            <li>Contains at least 1 uppercase letter</li>
            <li>Contains a special character (e.g. @ !)</li>
          </ul>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-xs-4">Confirm Password</label>
        <div class="col-xs-8">
          <input type="password" class="form-control" id="confirm_password" name="confirm_password" required>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-xs-4">Date of Birth</label>
        <div class="col-xs-8">
          <input type="date" class="form-control" id="dateOfBirth" name="dateOfBirth" required>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-xs-4">Security Question</label>
        <div class="col-xs-8">
          <select id="question1" name="question1" required>
            <option value="">--Please choose an option--</option>
            <option value="1">What was your childhood nickname?</option>
            <option value="2">In what city did you meet your spouse/significant other?</option>
            <option value="3">What is the name of your favorite childhood friend?</option>
            <option value="4">What is your oldest sibling's middle name?</option>
            <option value="5">What school did you attend for sixth grade?</option>
            <option value="6">What is your oldest cousin's first and last name?</option>
          </select>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-xs-4">Answer</label>
        <div class="col-xs-8">
          <input type="text" class="form-control" id="answer1" name="answer1" required>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-xs-4">Security Question</label>
        <div class="col-xs-8">
          <select id="question2" name="question2" required>
            <option value="">--Please choose an option--</option>
            <option value="1">In what city or town did your mother and father meet?</option>
            <option value="2">What was the last name of your third grade teacher?</option>
            <option value="3">In what city does your nearest sibling live?</option>
            <option value="4">What is your maternal grandmother's maiden name?</option>
            <option value="5">In what city or town was your first job?</option>
            <option value="6">Where were you when you first heard about 9/11?</option>
          </select>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-xs-4">Answer</label>
        <div class="col-xs-8">
          <input type="text" class="form-control" id="answer2" name="answer2" required>
        </div>
      </div>
      <div class="g-recaptcha" data-sitekey="<?php echo $this->sitekey; ?>"></div>
      <div class="form-group">
        <div class="col-xs-8 col-xs-offset-4">
          <p><label class="checkbox-inline"><input type="checkbox" required> I accept the <a href="#">Terms of Use</a> &amp; <a href="#">Privacy Policy</a>.</label></p>
          <button type="submit" class="btn btn-primary btn-lg">Sign Up</button>
        </div>
      </div>
    </form>
    <div class="text-center">Already have an account? <a href="../..">Login here</a></div>
  </div>
  <script src="../../js/sign_up.js"></script>
</body>

</html>